/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/posts/{id}": {
    /** 글 상세 조회 */
    get: operations["getPost"];
    /** 글 수정 */
    put: operations["modifyPost"];
    /** 글 삭제 */
    delete: operations["deletePost"];
  };
  "/api/v1/posts": {
    /** 글 리스트 */
    get: operations["getPosts"];
    /** 글 작성 */
    post: operations["writePost"];
  };
  "/api/v1/members/login": {
    /** 로그인, 로그인 성공시 accessToken, refreshToken 쿠키 설정 */
    post: operations["login"];
  };
  "/api/v1/members/join": {
    /** 회원가입 */
    post: operations["join"];
  };
  "/api/v1/posts/myList": {
    /** 내 글 리스트 */
    get: operations["getMyPosts"];
  };
  "/api/v1/posts/latest": {
    /** 최신 글 리스트 */
    get: operations["getLatestPosts"];
  };
  "/api/v1/b/{username}": {
    /** 특정 사용자의 글 리스트 */
    get: operations["getPostsByUsername"];
  };
  "/api/v1/b/{username}/{id}": {
    /** 특정 사용자의 글 상세 조회 */
    get: operations["getPostById"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    PostRequestDto: {
      title: string;
      body: string;
      published?: boolean;
    };
    RsDataObject: {
      resultCode: string;
      msg: string;
      data: Record<string, never>;
      /** Format: int32 */
      statusCode: number;
      fail: boolean;
      success: boolean;
    };
    LoginRequestDto: {
      username: string;
      password: string;
    };
    JoinRequestDto: {
      username: string;
      password: string;
      passwordConfirm: string;
    };
    GetItemsResponseBody: {
      items: components["schemas"]["PostDto"][];
    };
    PostDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      /** Format: int64 */
      authorId: number;
      authorName: string;
      title: string;
      body: string;
      published?: boolean;
    };
    RsDataGetItemsResponseBody: {
      resultCode: string;
      msg: string;
      data: components["schemas"]["GetItemsResponseBody"];
      /** Format: int32 */
      statusCode: number;
      fail: boolean;
      success: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** 글 상세 조회 */
  getPost: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 글 수정 */
  modifyPost: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 글 삭제 */
  deletePost: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 글 리스트 */
  getPosts: {
    parameters: {
      query?: {
        page?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGetItemsResponseBody"];
        };
      };
    };
  };
  /** 글 작성 */
  writePost: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 로그인, 로그인 성공시 accessToken, refreshToken 쿠키 설정 */
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 회원가입 */
  join: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinRequestDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 내 글 리스트 */
  getMyPosts: {
    parameters: {
      query?: {
        page?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 최신 글 리스트 */
  getLatestPosts: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 특정 사용자의 글 리스트 */
  getPostsByUsername: {
    parameters: {
      query?: {
        page?: number;
      };
      path: {
        username: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
  /** 특정 사용자의 글 상세 조회 */
  getPostById: {
    parameters: {
      path: {
        username: string;
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
    };
  };
}
